### ISSUE TITLE
Sample entity: RuntimeError -- can't modify frozen NilClass

### ISSUE THREAD

**Issue by mimadrid** [mikisvaz/rbbt-util#11]
For example
http://rbbt.bioinfo.cnio.es/entity/Sample/904079

**Comment by mikisvaz** [comment]
This issue uncovered a cascade of other issues that have all been addressed. Thanks!
In brief:
- WorkflowExplorer should not serve Sample entities
- HTML from job results is shared across different apps, not anymore
- Apps not serving a particular entity raise a more relevant exception
- The actual nil class error is a bit puzzling, the error stack seemed flawed. I might have fixed it though, but will probably creep back. Its a very minor thing it seems so lets leave it be.
