### ISSUE TITLE
Change MD5 digest with SHA

### ISSUE THREAD

**Issue by mikisvaz** [mikisvaz/rbbt-util#2]

**Comment by mikisvaz** [comment]
Not high-priority, will do when I have a chance

**Comment by mimadrid** [comment]
$ openssl speed md5 sha1
The 'numbers' are in 1000s of bytes per second processed.
type              16 bytes       64 bytes        256 bytes      1024 bytes    8192 bytes
md5              46660.70k   137328.89k   304102.74k   438556.60k   502383.30k
sha1             53450.59k   151591.42k   327178.24k   465790.29k   542228.48k

**Comment by mikisvaz** [comment]
Its ready to make the switch. It will require rebuilding all the infrastructures and recomputing all jobs in production, so the change is not worth it I think. I'm closing this for now.
